import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.Serializable;

public class BookRecordTest {

    @Test
    public void constructorValidGeneratesIdAndFields() {
        BookRecord bookRecord = new BookRecord("The Hobbit", "J.R.R. Tolkien", 1937);
        assertNotNull(bookRecord.getId(), "ID should be generated by constructor");
        // ID rule: first 3 chars of title + year + first 3 chars of author
        assertEquals("The1937J.R", bookRecord.getId());
        String s = bookRecord.toString();
        assertTrue(s.contains("The Hobbit"));
        assertTrue(s.contains("J.R.R. Tolkien"));
        assertTrue(s.contains("1937"));
    }

    @Test
    public void constructorInvalidArgumentsThrow() {
        assertThrows(IllegalArgumentException.class, () -> new BookRecord("", "Author", 2000));
        assertThrows(IllegalArgumentException.class, () -> new BookRecord("Title", "", 2000));
        assertThrows(IllegalArgumentException.class, () -> new BookRecord("Title", "Author", -1));
        assertThrows(IllegalArgumentException.class, () -> new BookRecord("Title", "Author", 3000));
    }

    @Test
    public void equalsConsidersTitleAuthorAndId() {
        BookRecord a = new BookRecord("The Hobbit", "J.R.R. Tolkien", 1937);
        BookRecord b = new BookRecord("The Hobbit", "J.R.R. Tolkien", 1937);
        assertTrue(a.equals(b));
    }

    @Test
    public void implementsDisplayableRecordAndSerializable() {
        BookRecord bookRecord = new BookRecord("The Hobbit", "J.R.R. Tolkien", 1937);
        assertTrue(bookRecord instanceof DisplayableRecord);
        assertTrue(bookRecord instanceof Serializable);
    }
}

